### ISSUE TITLE
Review the microcks plugin configuration

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks-jenkins-plugin#7]
I noticed a few things that needs to be reviewed on the microcks jenkins plugin:
 - the help popup url seems to be wrong in `src/main/resources/io/github/microcks/jenkins/plugin/MicrocksGlobalConfiguration/config.jelly` (`microcks-jenkins-pipeline` => `microcks-jenkins-plugin`)
 - the `disableSSLValidation` parameter cannot be set using the configuration-as-code plugin. Maybe because it has no getter/setter in `src/main/java/io/github/microcks/jenkins/plugin/model/MicrocksInstallation.java` ?
- the microcks tester timeout cannot be set using the configuration-as-code plugin.

**Comment by lbroudoux** [comment]
Hi @nmasse-itix 

sorry but I missed that one few months ago ...
Could you be elaborate a little bit on:

* the `disableSSLValidation` parameter cannot be set using the configuration-as-code plugin. Maybe because it has no getter/setter in `src/main/java/io/github/microcks/jenkins/plugin/model/MicrocksInstallation.java` ?

> This field has no setter and getter but the other fields have no setter too...

* the microcks tester timeout cannot be set using the configuration-as-code plugin.

> The `waitTime` and `waitUnit` are considered when using the DSL and the Builder if I remember well. Have you checked that ?

**Comment by lbroudoux** [comment]
`waitTime` attribute was incorrect and encoded as `wait` though not persisted. This has been fixed into #13 .
